//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int kId { get; set; }
        public string kAdi { get; set; }
        public string kSifre { get; set; }
    }
}
