//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int pid { get; set; }
     
        public string pAd { get; set; }
  
        public string pSoyad { get; set; }
        public string pTelNo { get; set; }
        public string yonetici { get; set; }
        public Nullable<int> dprFk { get; set; }
        public string Description
        {
            get
            {
                return pAd + " " + pSoyad;
            }
        }
        public virtual Departman Departman { get; set; }
    }
}
